### ISSUE TITLE
Build MAS App Issues

### ISSUE THREAD

**Issue by niku98** [clavin/electron-native-auth#8]
First of all, very thanks for your package.

I'm trying to build my app to upload to MAS. But I got the following error:

```
• electron-builder  version=25.1.8 os=24.2.0
  • loaded configuration  file=/Users/phammanh/Projects/**/**/electron-builder.yml
  • writing effective config  file=dist/builder-effective-config.yaml
  • executing @electron/rebuild  electronVersion=33.2.1 arch=x64 buildFromSource=false appDir=./
  • installing native dependencies  arch=x64
  • preparing       moduleName=better-sqlite3 arch=x64
  • finished        moduleName=better-sqlite3 arch=x64
  • preparing       moduleName=electron-native-auth arch=x64
  • finished        moduleName=electron-native-auth arch=x64
  • preparing       moduleName=node-mac-sign-in-with-apple arch=x64
  • finished        moduleName=node-mac-sign-in-with-apple arch=x64
  • preparing       moduleName=sqlite3 arch=x64
  • finished        moduleName=sqlite3 arch=x64
  • completed installing native dependencies
  • packaging       platform=mas arch=x64 electron=33.2.1 appOutDir=dist/mas-universal-x64-temp
  • executing @electron/rebuild  electronVersion=33.2.1 arch=arm64 buildFromSource=false appDir=./
  • installing native dependencies  arch=arm64
  • preparing       moduleName=better-sqlite3 arch=arm64
  • finished        moduleName=better-sqlite3 arch=arm64
  • preparing       moduleName=electron-native-auth arch=arm64
  • finished        moduleName=electron-native-auth arch=arm64
  • preparing       moduleName=node-mac-sign-in-with-apple arch=arm64
  • finished        moduleName=node-mac-sign-in-with-apple arch=arm64
  • preparing       moduleName=sqlite3 arch=arm64
  • finished        moduleName=sqlite3 arch=arm64
  • completed installing native dependencies
  • packaging       platform=mas arch=arm64 electron=33.2.1 appOutDir=dist/mas-universal-arm64-temp
  • packaging       platform=mas arch=universal electron=33.2.1 appOutDir=dist/mas-universal
  ⨯ Detected unique file "node_modules/electron-native-auth/build/Release/electron_native_auth.node.dSYM/Contents/Resources/Relocations/x86_64" in "/var/folders/89/5fkvhw5j2dn1s6qfxp9vbh840000gq/T/electron-universal-xkCKBV/Tmp.app/Contents/Resources/app.asar" not covered by allowList rule: "undefined"  failedTask=build stackTrace=Error: Detected unique file "node_modules/electron-native-auth/build/Release/electron_native_auth.node.dSYM/Contents/Resources/Relocations/x86_64" in "/var/folders/89/5fkvhw5j2dn1s6qfxp9vbh840000gq/T/electron-universal-xkCKBV/Tmp.app/Contents/Resources/app.asar" not covered by allowList rule: "undefined"
    at checkSingleArch (/Users/phammanh/Projects/**/**/node_modules/.pnpm/@electron+universal@2.0.1/node_modules/@electron/universal/src/asar-utils.ts:72:11)
    at mergeASARs (/Users/phammanh/Projects/**/**/node_modules/.pnpm/@electron+universal@2.0.1/node_modules/@electron/universal/src/asar-utils.ts:120:7)
    at makeUniversalApp (/Users/phammanh/Projects/**/**/node_modules/.pnpm/@electron+universal@2.0.1/node_modules/@electron/universal/src/index.ts:245:23)
    at MacPackager.doPack (/Users/phammanh/Projects/**/**/node_modules/.pnpm/app-builder-lib@25.1.8_dmg-builder@25.1.8_electron-builder-squirrel-windows@25.1.8/node_modules/app-builder-lib/src/macPackager.ts:153:9)
    at MacPackager.pack (/Users/phammanh/Projects/**/**/node_modules/.pnpm/app-builder-lib@25.1.8_dmg-builder@25.1.8_electron-builder-squirrel-windows@25.1.8/node_modules/app-builder-lib/src/macPackager.ts:205:9)
    at Packager.doBuild (/Users/phammanh/Projects/**/**/node_modules/.pnpm/app-builder-lib@25.1.8_dmg-builder@25.1.8_electron-builder-squirrel-windows@25.1.8/node_modules/app-builder-lib/src/packager.ts:459:9)
    at executeFinally (/Users/phammanh/Projects/**/**/node_modules/.pnpm/builder-util@25.1.7/node_modules/builder-util/src/promise.ts:12:14)
    at Packager.build (/Users/phammanh/Projects/**/**/node_modules/.pnpm/app-builder-lib@25.1.8_dmg-builder@25.1.8_electron-builder-squirrel-windows@25.1.8/node_modules/app-builder-lib/src/packager.ts:393:31)
    at executeFinally (/Users/phammanh/Projects/**/**/node_modules/.pnpm/builder-util@25.1.7/node_modules/builder-util/src/promise.ts:12:14)
```

Then, I solve that issue by setting `singleArchFiles: "*"` in electron builder config, references issue: https://github.com/electron-userland/electron-builder/issues/6862

After that, I built and signed successfully. But, when I upload to Testflight, I got these errors:

```
Asset validation failed (90278)
Invalid Bundle. The application bundle may not contain tools or frameworks provided by Apple, or using bundle identifiers in the 'com.apple.' namespace. Invalid bundle: [**.**.**.pkg/Payload/**.app/Contents/Resources/app.asar.unpacked/node_modules/electron-native-auth/build/Release/electron_native_auth.node.dSYM], with bundle identifier 'com.apple.xcode.dsym.electron_native_auth.node'. (ID: 875e0574-4d92-4288-917c-2c4fad587f82)

Asset validation failed (90277)
Invalid Bundle Identifier. The application bundle contains a tool or framework [**.**.**.pkg/Payload/**.app/Contents/Resources/app.asar.unpacked/node_modules/electron-native-auth/build/Release/electron_native_auth.node.dSYM] using the bundle identifier 'com.apple.xcode.dsym.electron_native_auth.node', which is not a valid bundle identifier. (ID: d22abb3c-0a3b-4a30-ba88-339d8a47fe3e)

Asset validation failed (90135)
Invalid bundle. The executable couldn’t be re-signed for upload to App Store Connect. The app may have been built or signed with unsupported or prerelease tools. (ID: aeeb6074-2666-4e4b-a2a4-64767e11c00c)
```

I got these errors after install `electron-native-auth`. Does someone have any idea?
Thanks.

**Device**: Mac Studio - M1 Max
**OS**: MacOS 15.2
**Electron**: 33.2.1
**Electron Builder**: 25.1.8

**Comment by angtho** [comment]
The issue is due to (what appears to be) temporary build files still present in the installed node_module during packaging, which cause the MAS upload validation process to fail because they reference internal Apple code.

You can resolve this by adding the following to your build script to remove the files. You will need to ensure this happens before packaging your app.

```
find ./node_modules/electron-native-auth/build -type f -not -name "*.o" -not -name "*.node" -not -name "*.stamp" -delete
find ./node_modules/electron-native-auth/build -type d -empty -delete
rm -rf ./node_modules/electron-native-auth/node-addon-api
rm -rf ./node_modules/electron-native-auth/build/Release/electron_native_auth.node.dSYM
```

**Comment by clavin** [comment]
Hi, thanks for the report!

As @angtho alluded to, this error occurs because the debug symbol information differs on each architecture.

I recommend you exclude the compiled `electron_native_auth.node.dSYM` directory from your app's package, or remove it if you're not using it.
